using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OrangeHRFinalProject.Entities.Concretes;

namespace OrangeHRFinalProject.DAL.EntityTypeConfigurations
{
    public class DistrictTypeConfiguration : IEntityTypeConfiguration<District>
    {
        public void Configure(EntityTypeBuilder<District> builder)
        {
            builder.HasKey(m => m.Id);
            builder.HasData(
                new District { Id = 1,  Name = "Seyhan", CityId = 1 },
                new District { Id = 2,  Name = "Ceyhan", CityId = 1 },
                new District { Id = 3,  Name = "Feke", CityId = 1 },
                new District { Id = 4,  Name = "Karaisalı", CityId = 1 },
                new District { Id = 5,  Name = "Karataş", CityId = 1 },
                new District { Id = 6,  Name = "Kozan", CityId = 1 },
                new District { Id = 7,  Name = "Pozantı", CityId = 1 },
                new District { Id = 8,  Name = "Saimbeyli", CityId = 1 },
                new District { Id = 9,  Name = "Tufanbeyli", CityId = 1 },
                new District { Id = 10, Name = "Yumurtalık", CityId = 1 },
                new District { Id = 11, Name = "Yüreğir", CityId = 1 },
                new District { Id = 12, Name = "Aladağ", CityId = 1 },
                new District { Id = 13, Name = "İmamoğlu", CityId = 1 },
                new District { Id = 14, Name = "Sarıçam", CityId = 1 },
                new District { Id = 15, Name = "Çukurova", CityId = 1 },
                new District { Id = 16, Name = "Adıyaman Merkez", CityId = 2 },
                new District { Id = 17, Name = "Besni", CityId = 2 },
                new District { Id = 18, Name = "Çelikhan", CityId = 2 },
                new District { Id = 19, Name = "Gerger", CityId = 2 },
                new District { Id = 20, Name = "Gölbaşı / Adıyaman", CityId = 2 },
                new District { Id = 21, Name = "Kahta", CityId = 2 },
                new District { Id = 22, Name = "Samsat", CityId = 2 },
                new District { Id = 23, Name = "Sincik", CityId = 2 },
                new District { Id = 24, Name = "Tut", CityId = 2 },
                new District { Id = 25, Name = "Afyonkarahisar Merkez", CityId = 3 },
                new District { Id = 26, Name = "Bolvadin", CityId = 3 },
                new District { Id = 27, Name = "Çay", CityId = 3 },
                new District { Id = 28, Name = "Dazkırı", CityId = 3 },
                new District { Id = 29, Name = "Dinar", CityId = 3 },
                new District { Id = 30, Name = "Emirdağ", CityId = 3 },
                new District { Id = 31, Name = "İhsaniye", CityId = 3 },
                new District { Id = 32, Name = "Sandıklı", CityId = 3 },
                new District { Id = 33, Name = "Sinanpaşa", CityId = 3 },
                new District { Id = 34, Name = "Sultandağı", CityId = 3 },
                new District { Id = 35, Name = "Şuhut", CityId = 3 },
                new District { Id = 36, Name = "Başmakçı", CityId = 3 },
                new District { Id = 37, Name = "Bayat / Afyonkarahisar", CityId = 3 },
                new District { Id = 38, Name = "İscehisar", CityId = 3 },
                new District { Id = 39, Name = "Çobanlar", CityId = 3 },
                new District { Id = 40, Name = "Evciler", CityId = 3 },
                new District { Id = 41, Name = "Hocalar", CityId = 3 },
                new District { Id = 42, Name = "Kızılören", CityId = 3 },
                new District { Id = 43, Name = "Ağrı Merkez", CityId = 4 },
                new District { Id = 44, Name = "Diyadin", CityId = 4 },
                new District { Id = 45, Name = "Doğubayazıt", CityId = 4 },
                new District { Id = 46, Name = "Eleşkirt", CityId = 4 },
                new District { Id = 47, Name = "Hamur", CityId = 4 },
                new District { Id = 48, Name = "Patnos", CityId = 4 },
                new District { Id = 49, Name = "Taşlıçay", CityId = 4 },
                new District { Id = 50, Name = "Tutak", CityId = 4 },
                new District { Id = 51, Name = "Amasya Merkez", CityId = 5 },
                new District { Id = 52, Name = "Göynücek", CityId = 5 },
                new District { Id = 53, Name = "Gümüşhacıköy", CityId = 5 },
                new District { Id = 54, Name = "Merzifon", CityId = 5 },
                new District { Id = 55, Name = "Suluova", CityId = 5 },
                new District { Id = 56, Name = "Taşova", CityId = 5 },
                new District { Id = 57, Name = "Hamamözü", CityId = 5 },
                new District { Id = 58, Name = "Altındağ", CityId = 6 },
                new District { Id = 59, Name = "Ayaş", CityId = 6 },
                new District { Id = 60, Name = "Bala", CityId = 6 },
                new District { Id = 61, Name = "Beypazarı", CityId = 6 },
                new District { Id = 62, Name = "Çamlıdere", CityId = 6 },
                new District { Id = 63, Name = "Çankaya", CityId = 6 },
                new District { Id = 64, Name = "Çubuk", CityId = 6 },
                new District { Id = 65, Name = "Elmadağ", CityId = 6 },
                new District { Id = 66, Name = "Güdül", CityId = 6 },
                new District { Id = 67, Name = "Haymana", CityId = 6 },
                new District { Id = 68, Name = "Kalecik", CityId = 6 },
                new District { Id = 69, Name = "Kızılcahamam", CityId = 6 },
                new District { Id = 70, Name = "Nallıhan", CityId = 6 },
                new District { Id = 71, Name = "Polatlı", CityId = 6 },
                new District { Id = 72, Name = "Şereflikoçhisar", CityId = 6 },
                new District { Id = 73, Name = "Yenimahalle", CityId = 6 },
                new District { Id = 74, Name = "Gölbaşı / Ankara", CityId = 6 },
                new District { Id = 75, Name = "Keçiören", CityId = 6 },
                new District { Id = 76, Name = "Mamak", CityId = 6 },
                new District { Id = 77, Name = "Sincan", CityId = 6 },
                new District { Id = 78, Name = "Kazan", CityId = 6 },
                new District { Id = 79, Name = "Akyurt", CityId = 6 },
                new District { Id = 80, Name = "Etimesgut", CityId = 6 },
                new District { Id = 81, Name = "Evren", CityId = 6 },
                new District { Id = 82, Name = "Pursaklar", CityId = 6 },
                new District { Id = 83, Name = "Akseki", CityId = 7 },
                new District { Id = 84, Name = "Alanya", CityId = 7 },
                new District { Id = 85, Name = "Elmalı", CityId = 7 },
                new District { Id = 86, Name = "Finike", CityId = 7 },
                new District { Id = 87, Name = "Gazipaşa", CityId = 7 },
                new District { Id = 88, Name = "Gündoğmuş", CityId = 7 },
                new District { Id = 89, Name = "Kaş", CityId = 7 },
                new District { Id = 90, Name = "Korkuteli", CityId = 7 },
                new District { Id = 91, Name = "Kumluca", CityId = 7 },
                new District { Id = 92, Name = "Manavgat", CityId = 7 },
                new District { Id = 93,  Name = "Serik", CityId = 7 },
                new District { Id = 94,  Name = "Demre", CityId = 7 },
                new District { Id = 95,  Name = "İbradı", CityId = 7 },
                new District { Id = 96,  Name = "Kemer / Antalya", CityId = 7 },
                new District { Id = 97,  Name = "Aksu / Antalya", CityId = 7 },
                new District { Id = 98,  Name = "Döşemealtı", CityId = 7 },
                new District { Id = 99,  Name = "Kepez", CityId = 7 },
                new District { Id = 100, Name = "Konyaaltı", CityId = 7 },
                new District { Id = 101, Name = "Muratpaşa", CityId = 7 },
                new District { Id = 102, Name = "Ardanuç", CityId = 8 },
                new District { Id = 103, Name = "Arhavi", CityId = 8 },
                new District { Id = 104, Name = "Artvin Merkez", CityId = 8 },
                new District { Id = 105, Name = "Borçka", CityId = 8 },
                new District { Id = 106, Name = "Hopa", CityId = 8 },
                new District { Id = 107, Name = "Şavşat", CityId = 8 },
                new District { Id = 108, Name = "Yusufeli", CityId = 8 },
                new District { Id = 109, Name = "Murgul", CityId = 8 },
                new District { Id = 110, Name = "Bozdoğan", CityId = 9 },
                new District { Id = 111, Name = "Çine", CityId = 9 },
                new District { Id = 112, Name = "Germencik", CityId = 9 },
                new District { Id = 113, Name = "Karacasu", CityId = 9 },
                new District { Id = 114, Name = "Koçarlı", CityId = 9 },
                new District { Id = 115, Name = "Kuşadası", CityId = 9 },
                new District { Id = 116, Name = "Kuyucak", CityId = 9 },
                new District { Id = 117, Name = "Nazilli", CityId = 9 },
                new District { Id = 118, Name = "Söke", CityId = 9 },
                new District { Id = 119, Name = "Sultanhisar", CityId = 9 },
                new District { Id = 120, Name = "Yenipazar / Aydın", CityId = 9 },
                new District { Id = 121, Name = "Buharkent", CityId = 9 },
                new District { Id = 122, Name = "İncirliova", CityId = 9 },
                new District { Id = 123, Name = "Karpuzlu", CityId = 9 },
                new District { Id = 124, Name = "Köşk", CityId = 9 },
                new District { Id = 125, Name = "Didim", CityId = 9 },
                new District { Id = 126, Name = "Efeler", CityId = 9 },
                new District { Id = 127, Name = "Ayvalık", CityId = 10 },
                new District { Id = 128, Name = "Balya", CityId = 10 },
                new District { Id = 129, Name = "Bandırma", CityId = 10 },
                new District { Id = 130, Name = "Bigadiç", CityId = 10 },
                new District { Id = 131, Name = "Burhaniye", CityId = 10 },
                new District { Id = 132, Name = "Dursunbey", CityId = 10 },
                new District { Id = 133, Name = "Edremit / Balıkesir", CityId = 10 },
                new District { Id = 134, Name = "Erdek", CityId = 10 },
                new District { Id = 135, Name = "Gönen / Balıkesir", CityId = 10 },
                new District { Id = 136, Name = "Havran", CityId = 10 },
                new District { Id = 137, Name = "İvrindi", CityId = 10 },
                new District { Id = 138, Name = "Kepsut", CityId = 10 },
                new District { Id = 139, Name = "Manyas", CityId = 10 },
                new District { Id = 140, Name = "Savaştepe", CityId = 10 },
                new District { Id = 141, Name = "Sındırgı", CityId = 10 },
                new District { Id = 142, Name = "Susurluk", CityId = 10 },
                new District { Id = 143, Name = "Marmara", CityId = 10 },
                new District { Id = 144, Name = "Gömeç", CityId = 10 },
                new District { Id = 145, Name = "Altıeylül", CityId = 10 },
                new District { Id = 146, Name = "Karesi", CityId = 10 },
                new District { Id = 147, Name = "Bilecik Merkez", CityId = 11 },
                new District { Id = 148, Name = "Bozüyük", CityId = 11 },
                new District { Id = 149, Name = "Gölpazarı", CityId = 11 },
                new District { Id = 150, Name = "Osmaneli", CityId = 11 },
                new District { Id = 151, Name = "Pazaryeri", CityId = 11 },
                new District { Id = 152, Name = "Söğüt", CityId = 11 },
                new District { Id = 153, Name = "Yenipazar / Bilecik", CityId = 11 },
                new District { Id = 154, Name = "İnhisar", CityId = 11 },
                new District { Id = 155, Name = "Bingöl Merkez", CityId = 12 },
                new District { Id = 156, Name = "Genç", CityId = 12 },
                new District { Id = 157, Name = "Karlıova", CityId = 12 },
                new District { Id = 158, Name = "Kiğı", CityId = 12 },
                new District { Id = 159, Name = "Solhan", CityId = 12 },
                new District { Id = 160, Name = "Adaklı", CityId = 12 },
                new District { Id = 161, Name = "Yayladere", CityId = 12 },
                new District { Id = 162, Name = "Yedisu", CityId = 12 },
                new District { Id = 163, Name = "Adilcevaz", CityId = 13 },
                new District { Id = 164, Name = "Ahlat", CityId = 13 },
                new District { Id = 165, Name = "Bitlis Merkez", CityId = 13 },
                new District { Id = 166, Name = "Hizan", CityId = 13 },
                new District { Id = 167, Name = "Mutki", CityId = 13 },
                new District { Id = 168, Name = "Tatvan", CityId = 13 },
                new District { Id = 169, Name = "Güroymak", CityId = 13 },
                new District { Id = 170, Name = "Bolu Merkez", CityId = 14 },
                new District { Id = 171, Name = "Gerede", CityId = 14 },
                new District { Id = 172, Name = "Göynük", CityId = 14 },
                new District { Id = 173, Name = "Kıbrıscık", CityId = 14 },
                new District { Id = 174, Name = "Mengen", CityId = 14 },
                new District { Id = 175, Name = "Mudurnu", CityId = 14 },
                new District { Id = 176, Name = "Seben", CityId = 14 },
                new District { Id = 177, Name = "Dörtdivan", CityId = 14 },
                new District { Id = 178, Name = "Yeniçağa", CityId = 14 },
                new District { Id = 179, Name = "Ağlasun", CityId = 15 },
                new District { Id = 180, Name = "Bucak", CityId = 15 },
                new District { Id = 181, Name = "Burdur Merkez", CityId = 15 },
                new District { Id = 182, Name = "Gölhisar", CityId = 15 },
                new District { Id = 183, Name = "Tefenni", CityId = 15 },
                new District { Id = 184, Name = "Yeşilova", CityId = 15 },
                new District { Id = 185, Name = "Karamanlı", CityId = 15 },
                new District { Id = 186, Name = "Kemer / Burdur", CityId = 15 },
                new District { Id = 187, Name = "Altınyayla / Burdur", CityId = 15 },
                new District { Id = 188, Name = "Çavdır", CityId = 15 },
                new District { Id = 189, Name = "Çeltikçi", CityId = 15 },
                new District { Id = 190, Name = "Gemlik", CityId = 16 },
                new District { Id = 191, Name = "İnegöl", CityId = 16 },
                new District { Id = 192, Name = "İznik", CityId = 16 },
                new District { Id = 193, Name = "Karacabey", CityId = 16 },
                new District { Id = 194, Name = "Keles", CityId = 16 },
                new District { Id = 195, Name = "Mudanya", CityId = 16 },
                new District { Id = 196, Name = "Mustafakemalpaşa", CityId = 16 },
                new District { Id = 197, Name = "Orhaneli", CityId = 16 },
                new District { Id = 198, Name = "Orhangazi", CityId = 16 },
                new District { Id = 199, Name = "Yenişehir / Bursa", CityId = 16 },
                new District { Id = 200, Name = "Büyükorhan", CityId = 16 },
                new District { Id = 201, Name = "Harmancık", CityId = 16 },
                new District { Id = 202, Name = "Nilüfer", CityId = 16 },
                new District { Id = 203, Name = "Osmangazi", CityId = 16 },
                new District { Id = 204, Name = "Yıldırım", CityId = 16 },
                new District { Id = 205, Name = "Gürsu", CityId = 16 },
                new District { Id = 206, Name = "Kestel", CityId = 16 },
                new District { Id = 207, Name = "Ayvacık / Çanakkale", CityId = 17 },
                new District { Id = 208, Name = "Bayramiç", CityId = 17 },
                new District { Id = 209, Name = "Biga", CityId = 17 },
                new District { Id = 210, Name = "Bozcaada", CityId = 17 },
                new District { Id = 211, Name = "Çan", CityId = 17 },
                new District { Id = 212, Name = "Çanakkale Merkez", CityId = 17 },
                new District { Id = 213, Name = "Eceabat", CityId = 17 },
                new District { Id = 214, Name = "Ezine", CityId = 17 },
                new District { Id = 215, Name = "Gelibolu", CityId = 17 },
                new District { Id = 216, Name = "Gökçeada", CityId = 17 },
                new District { Id = 217, Name = "Lapseki", CityId = 17 },
                new District { Id = 218, Name = "Yenice / Çanakkale", CityId = 17 },
                new District { Id = 219, Name = "Çankırı Merkez", CityId = 18 },
                new District { Id = 220, Name = "Çerkeş", CityId = 18 },
                new District { Id = 221, Name = "Eldivan", CityId = 18 },
                new District { Id = 222, Name = "Ilgaz", CityId = 18 },
                new District { Id = 223, Name = "Kurşunlu", CityId = 18 },
                new District { Id = 224, Name = "Orta", CityId = 18 },
                new District { Id = 225, Name = "Şabanözü", CityId = 18 },
                new District { Id = 226, Name = "Yapraklı", CityId = 18 },
                new District { Id = 227, Name = "Atkaracalar", CityId = 18 },
                new District { Id = 228, Name = "Kızılırmak", CityId = 18 },
                new District { Id = 229, Name = "Bayramören", CityId = 18 },
                new District { Id = 230, Name = "Korgun", CityId = 18 },
                new District { Id = 231, Name = "Alaca", CityId = 19 },
                new District { Id = 232, Name = "Bayat / Çorum", CityId = 19 },
                new District { Id = 233, Name = "Çorum Merkez", CityId = 19 },
                new District { Id = 234, Name = "İskilip", CityId = 19 },
                new District { Id = 235, Name = "Kargı", CityId = 19 },
                new District { Id = 236, Name = "Mecitözü", CityId = 19 },
                new District { Id = 237, Name = "Ortaköy / Çorum", CityId = 19 },
                new District { Id = 238, Name = "Osmancık", CityId = 19 },
                new District { Id = 239, Name = "Sungurlu", CityId = 19 },
                new District { Id = 240, Name = "Boğazkale", CityId = 19 },
                new District { Id = 241, Name = "Uğurludağ", CityId = 19 },
                new District { Id = 242, Name = "Dodurga", CityId = 19 },
                new District { Id = 243, Name = "Laçin", CityId = 19 },
                new District { Id = 244, Name = "Oğuzlar", CityId = 19 },
                new District { Id = 245, Name = "Acıpayam", CityId = 20 },
                new District { Id = 246, Name = "Buldan", CityId = 20 },
                new District { Id = 247, Name = "Çal", CityId = 20 },
                new District { Id = 248, Name = "Çameli", CityId = 20 },
                new District { Id = 249, Name = "Çardak", CityId = 20 },
                new District { Id = 250, Name = "Çivril", CityId = 20 },
                new District { Id = 251, Name = "Güney", CityId = 20 },
                new District { Id = 252, Name = "Kale / Denizli", CityId = 20 },
                new District { Id = 253, Name = "Sarayköy", CityId = 20 },
                new District { Id = 254, Name = "Tavas", CityId = 20 },
                new District { Id = 255, Name = "Babadağ", CityId = 20 },
                new District { Id = 256, Name = "Bekilli", CityId = 20 },
                new District { Id = 257, Name = "Honaz", CityId = 20 },
                new District { Id = 258, Name = "Serinhisar", CityId = 20 },
                new District { Id = 259, Name = "Pamukkale", CityId = 20 },
                new District { Id = 260, Name = "Baklan", CityId = 20 },
                new District { Id = 261, Name = "Beyağaç", CityId = 20 },
                new District { Id = 262, Name = "Bozkurt / Denizli", CityId = 20 },
                new District { Id = 263, Name = "Merkezefendi", CityId = 20 },
                new District { Id = 264, Name = "Bismil", CityId = 21 },
                new District { Id = 265, Name = "Çermik", CityId = 21 },
                new District { Id = 266, Name = "Çınar", CityId = 21 },
                new District { Id = 267, Name = "Çüngüş", CityId = 21 },
                new District { Id = 268, Name = "Dicle", CityId = 21 },
                new District { Id = 269, Name = "Ergani", CityId = 21 },
                new District { Id = 270, Name = "Hani", CityId = 21 },
                new District { Id = 271, Name = "Hazro", CityId = 21 },
                new District { Id = 272, Name = "Kulp", CityId = 21 },
                new District { Id = 273, Name = "Lice", CityId = 21 },
                new District { Id = 274, Name = "Silvan", CityId = 21 },
                new District { Id = 275, Name = "Eğil", CityId = 21 },
                new District { Id = 276, Name = "Kocaköy", CityId = 21 },
                new District { Id = 277, Name = "Bağlar", CityId = 21 },
                new District { Id = 278, Name = "Kayapınar", CityId = 21 },
                new District { Id = 279, Name = "Sur", CityId = 21 },
                new District { Id = 280, Name = "Yenişehir / Diyarbakır", CityId = 21 },
                new District { Id = 281, Name = "Edirne Merkez", CityId = 22 },
                new District { Id = 282, Name = "Enez", CityId = 22 },
                new District { Id = 283, Name = "Havsa", CityId = 22 },
                new District { Id = 284, Name = "İpsala", CityId = 22 },
                new District { Id = 285, Name = "Keşan", CityId = 22 },
                new District { Id = 286, Name = "Lalapaşa", CityId = 22 },
                new District { Id = 287, Name = "Meriç", CityId = 22 },
                new District { Id = 288, Name = "Uzunköprü", CityId = 22 },
                new District { Id = 289, Name = "Süloğlu", CityId = 22 },
                new District { Id = 290, Name = "Ağın", CityId = 23 },
                new District { Id = 291, Name = "Baskil", CityId = 23 },
                new District { Id = 292, Name = "Elazığ Merkez", CityId = 23 },
                new District { Id = 293, Name = "Karakoçan", CityId = 23 },
                new District { Id = 294, Name = "Keban", CityId = 23 },
                new District { Id = 295, Name = "Maden", CityId = 23 },
                new District { Id = 296, Name = "Palu", CityId = 23 },
                new District { Id = 297, Name = "Sivrice", CityId = 23 },
                new District { Id = 298, Name = "Arıcak", CityId = 23 },
                new District { Id = 299, Name = "Kovancılar", CityId = 23 },
                new District { Id = 300, Name = "Alacakaya", CityId = 23 },
                new District { Id = 301, Name = "Çayırlı", CityId = 24 },
                new District { Id = 302, Name = "Erzincan Merkez", CityId = 24 },
                new District { Id = 303, Name = "İliç", CityId = 24 },
                new District { Id = 304, Name = "Kemah", CityId = 24 },
                new District { Id = 305, Name = "Kemaliye", CityId = 24 },
                new District { Id = 306, Name = "Refahiye", CityId = 24 },
                new District { Id = 307, Name = "Tercan", CityId = 24 },
                new District { Id = 308, Name = "Üzümlü", CityId = 24 },
                new District { Id = 309, Name = "Otlukbeli", CityId = 24 },
                new District { Id = 310, Name = "Aşkale", CityId = 25 },
                new District { Id = 311, Name = "Çat", CityId = 25 },
                new District { Id = 312, Name = "Hınıs", CityId = 25 },
                new District { Id = 313, Name = "Horasan", CityId = 25 },
                new District { Id = 314, Name = "İspir", CityId = 25 },
                new District { Id = 315, Name = "Karayazı", CityId = 25 },
                new District { Id = 316, Name = "Narman", CityId = 25 },
                new District { Id = 317, Name = "Oltu", CityId = 25 },
                new District { Id = 318, Name = "Olur", CityId = 25 },
                new District { Id = 319, Name = "Pasinler", CityId = 25 },
                new District { Id = 320, Name = "Şenkaya", CityId = 25 },
                new District { Id = 321, Name = "Tekman", CityId = 25 },
                new District { Id = 322, Name = "Tortum", CityId = 25 },
                new District { Id = 323, Name = "Karaçoban", CityId = 25 },
                new District { Id = 324, Name = "Uzundere", CityId = 25 },
                new District { Id = 325, Name = "Pazaryolu", CityId = 25 },
                new District { Id = 326, Name = "Aziziye", CityId = 25 },
                new District { Id = 327, Name = "Köprüköy", CityId = 25 },
                new District { Id = 328, Name = "Palandöken", CityId = 25 },
                new District { Id = 329, Name = "Yakutiye", CityId = 25 },
                new District { Id = 330, Name = "Çifteler", CityId = 26 },
                new District { Id = 331, Name = "Mahmudiye", CityId = 26 },
                new District { Id = 332, Name = "Mihalıççık", CityId = 26 },
                new District { Id = 333, Name = "Sarıcakaya", CityId = 26 },
                new District { Id = 334, Name = "Seyitgazi", CityId = 26 },
                new District { Id = 335, Name = "Sivrihisar", CityId = 26 },
                new District { Id = 336, Name = "Alpu", CityId = 26 },
                new District { Id = 337, Name = "Beylikova", CityId = 26 },
                new District { Id = 338, Name = "İnönü", CityId = 26 },
                new District { Id = 339, Name = "Günyüzü", CityId = 26 },
                new District { Id = 340, Name = "Han", CityId = 26 },
                new District { Id = 341, Name = "Mihalgazi", CityId = 26 },
                new District { Id = 342, Name = "Odunpazarı", CityId = 26 },
                new District { Id = 343, Name = "Tepebaşı", CityId = 26 },
                new District { Id = 344, Name = "Araban", CityId = 27 },
                new District { Id = 345, Name = "İslahiye", CityId = 27 },
                new District { Id = 346, Name = "Nizip", CityId = 27 },
                new District { Id = 347, Name = "Oğuzeli", CityId = 27 },
                new District { Id = 348, Name = "Yavuzeli", CityId = 27 },
                new District { Id = 349, Name = "Şahinbey", CityId = 27 },
                new District { Id = 350, Name = "Şehitkamil", CityId = 27 },
                new District { Id = 351, Name = "Karkamış", CityId = 27 },
                new District { Id = 352, Name = "Nurdağı", CityId = 27 },
                new District { Id = 353, Name = "Alucra", CityId = 28 },
                new District { Id = 354, Name = "Bulancak", CityId = 28 },
                new District { Id = 355, Name = "Dereli", CityId = 28 },
                new District { Id = 356, Name = "Espiye", CityId = 28 },
                new District { Id = 357, Name = "Eynesil", CityId = 28 },
                new District { Id = 358, Name = "Giresun Merkez", CityId = 28 },
                new District { Id = 359, Name = "Görele", CityId = 28 },
                new District { Id = 360, Name = "Keşap", CityId = 28 },
                new District { Id = 361, Name = "Şebinkarahisar", CityId = 28 },
                new District { Id = 362, Name = "Tirebolu", CityId = 28 },
                new District { Id = 363, Name = "Piraziz", CityId = 28 },
                new District { Id = 364, Name = "Yağlıdere", CityId = 28 },
                new District { Id = 365, Name = "Çamoluk", CityId = 28 },
                new District { Id = 366, Name = "Çanakçı", CityId = 28 },
                new District { Id = 367, Name = "Doğankent", CityId = 28 },
                new District { Id = 368, Name = "Güce", CityId = 28 },
                new District { Id = 369, Name = "Gümüşhane Merkez", CityId = 29 },
                new District { Id = 370, Name = "Kelkit", CityId = 29 },
                new District { Id = 371, Name = "Şiran", CityId = 29 },
                new District { Id = 372, Name = "Torul", CityId = 29 },
                new District { Id = 373, Name = "Köse", CityId = 29 },
                new District { Id = 374, Name = "Kürtün", CityId = 29 },
                new District { Id = 375, Name = "Çukurca", CityId = 30 },
                new District { Id = 376, Name = "Hakkari Merkez", CityId = 30 },
                new District { Id = 377, Name = "Şemdinli", CityId = 30 },
                new District { Id = 378, Name = "Yüksekova", CityId = 30 },
                new District { Id = 379, Name = "Altınözü", CityId = 31 },
                new District { Id = 380, Name = "Dörtyol", CityId = 31 },
                new District { Id = 381, Name = "Hassa", CityId = 31 },
                new District { Id = 382, Name = "İskenderun", CityId = 31 },
                new District { Id = 383, Name = "Kırıkhan", CityId = 31 },
                new District { Id = 384, Name = "Reyhanlı", CityId = 31 },
                new District { Id = 385, Name = "Samandağ", CityId = 31 },
                new District { Id = 386, Name = "Yayladağı", CityId = 31 },
                new District { Id = 387, Name = "Erzin", CityId = 31 },
                new District { Id = 388, Name = "Belen", CityId = 31 },
                new District { Id = 389, Name = "Kumlu", CityId = 31 },
                new District { Id = 390, Name = "Antakya", CityId = 31 },
                new District { Id = 391, Name = "Arsuz", CityId = 31 },
                new District { Id = 392, Name = "Defne", CityId = 31 },
                new District { Id = 393, Name = "Payas", CityId = 31 },
                new District { Id = 394, Name = "Atabey", CityId = 32 },
                new District { Id = 395, Name = "Eğirdir", CityId = 32 },
                new District { Id = 396, Name = "Gelendost", CityId = 32 },
                new District { Id = 397, Name = "Isparta Merkez", CityId = 32 },
                new District { Id = 398, Name = "Keçiborlu", CityId = 32 },
                new District { Id = 399, Name = "Senirkent", CityId = 32 },
                new District { Id = 400, Name = "Sütçüler", CityId = 32 },
                new District { Id = 401, Name = "Şarkikaraağaç", CityId = 32 },
                new District { Id = 402, Name = "Uluborlu", CityId = 32 },
                new District { Id = 403, Name = "Yalvaç", CityId = 32 },
                new District { Id = 404, Name = "Aksu / Isparta", CityId = 32 },
                new District { Id = 405, Name = "Gönen / Isparta", CityId = 32 },
                new District { Id = 406, Name = "Yenişarbademli", CityId = 32 },
                new District { Id = 407, Name = "Anamur", CityId = 33 },
                new District { Id = 408, Name = "Erdemli", CityId = 33 },
                new District { Id = 409, Name = "Gülnar", CityId = 33 },
                new District { Id = 410, Name = "Mut", CityId = 33 },
                new District { Id = 411, Name = "Silifke", CityId = 33 },
                new District { Id = 412, Name = "Tarsus", CityId = 33 },
                new District { Id = 413, Name = "Aydıncık / Mersin", CityId = 33 },
                new District { Id = 414, Name = "Bozyazı", CityId = 33 },
                new District { Id = 415, Name = "Çamlıyayla", CityId = 33 },
                new District { Id = 416, Name = "Akdeniz", CityId = 33 },
                new District { Id = 417, Name = "Mezitli", CityId = 33 },
                new District { Id = 418, Name = "Toroslar", CityId = 33 },
                new District { Id = 419, Name = "Yenişehir / Mersin", CityId = 33 },
                new District { Id = 420, Name = "Adalar", CityId = 34 },
                new District { Id = 421, Name = "Bakırköy", CityId = 34 },
                new District { Id = 422, Name = "Beşiktaş", CityId = 34 },
                new District { Id = 423, Name = "Beykoz", CityId = 34 },
                new District { Id = 424, Name = "Beyoğlu", CityId = 34 },
                new District { Id = 425, Name = "Çatalca", CityId = 34 },
                new District { Id = 426, Name = "Eyüp", CityId = 34 },
                new District { Id = 427, Name = "Fatih", CityId = 34 },
                new District { Id = 428, Name = "Gaziosmanpaşa", CityId = 34 },
                new District { Id = 429, Name = "Kadıköy", CityId = 34 },
                new District { Id = 430, Name = "Kartal", CityId = 34 },
                new District { Id = 431, Name = "Sarıyer", CityId = 34 },
                new District { Id = 432, Name = "Silivri", CityId = 34 },
                new District { Id = 433, Name = "Şile", CityId = 34 },
                new District { Id = 434, Name = "Şişli", CityId = 34 },
                new District { Id = 435, Name = "Üsküdar", CityId = 34 },
                new District { Id = 436, Name = "Zeytinburnu", CityId = 34 },
                new District { Id = 437, Name = "Büyükçekmece", CityId = 34 },
                new District { Id = 438, Name = "Kağıthane", CityId = 34 },
                new District { Id = 439, Name = "Küçükçekmece", CityId = 34 },
                new District { Id = 440, Name = "Pendik", CityId = 34 },
                new District { Id = 441, Name = "Ümraniye", CityId = 34 },
                new District { Id = 442, Name = "Bayrampaşa", CityId = 34 },
                new District { Id = 443, Name = "Avcılar", CityId = 34 },
                new District { Id = 444, Name = "Bağcılar", CityId = 34 },
                new District { Id = 445, Name = "Bahçelievler", CityId = 34 },
                new District { Id = 446, Name = "Güngören", CityId = 34 },
                new District { Id = 447, Name = "Maltepe", CityId = 34 },
                new District { Id = 448, Name = "Sultanbeyli", CityId = 34 },
                new District { Id = 449, Name = "Tuzla", CityId = 34 },
                new District { Id = 450, Name = "Esenler", CityId = 34 },
                new District { Id = 451, Name = "Arnavutköy", CityId = 34 },
                new District { Id = 452, Name = "Ataşehir", CityId = 34 },
                new District { Id = 453, Name = "Başakşehir", CityId = 34 },
                new District { Id = 454, Name = "Beylikdüzü", CityId = 34 },
                new District { Id = 455, Name = "Çekmeköy", CityId = 34 },
                new District { Id = 456, Name = "Esenyurt", CityId = 34 },
                new District { Id = 457, Name = "Sancaktepe", CityId = 34 },
                new District { Id = 458, Name = "Sultangazi", CityId = 34 },
                new District { Id = 459, Name = "Aliağa", CityId = 35 },
                new District { Id = 460, Name = "Bayındır", CityId = 35 },
                new District { Id = 461, Name = "Bergama", CityId = 35 },
                new District { Id = 462, Name = "Bornova", CityId = 35 },
                new District { Id = 463, Name = "Çeşme", CityId = 35 },
                new District { Id = 464, Name = "Dikili", CityId = 35 },
                new District { Id = 465, Name = "Foça", CityId = 35 },
                new District { Id = 466, Name = "Karaburun", CityId = 35 },
                new District { Id = 467, Name = "Karşıyaka", CityId = 35 },
                new District { Id = 468, Name = "Kemalpaşa / İzmir", CityId = 35 },
                new District { Id = 469, Name = "Kınık", CityId = 35 },
                new District { Id = 470, Name = "Kiraz", CityId = 35 },
                new District { Id = 471, Name = "Menemen", CityId = 35 },
                new District { Id = 472, Name = "Ödemiş", CityId = 35 },
                new District { Id = 473, Name = "Seferihisar", CityId = 35 },
                new District { Id = 474, Name = "Selçuk", CityId = 35 },
                new District { Id = 475, Name = "Tire", CityId = 35 },
                new District { Id = 476, Name = "Torbalı", CityId = 35 },
                new District { Id = 477, Name = "Urla", CityId = 35 },
                new District { Id = 478, Name = "Beydağ", CityId = 35 },
                new District { Id = 479, Name = "Buca", CityId = 35 },
                new District { Id = 480, Name = "Konak", CityId = 35 },
                new District { Id = 481, Name = "Menderes", CityId = 35 },
                new District { Id = 482, Name = "Balçova", CityId = 35 },
                new District { Id = 483, Name = "Çiğli", CityId = 35 },
                new District { Id = 484, Name = "Gaziemir", CityId = 35 },
                new District { Id = 485, Name = "Narlıdere", CityId = 35 },
                new District { Id = 486, Name = "Güzelbahçe", CityId = 35 },
                new District { Id = 487, Name = "Bayraklı", CityId = 35 },
                new District { Id = 488, Name = "Karabağlar", CityId = 35 },
                new District { Id = 489, Name = "Arpaçay", CityId = 36 },
                new District { Id = 490, Name = "Digor", CityId = 36 },
                new District { Id = 491, Name = "Kağızman", CityId = 36 },
                new District { Id = 492, Name = "Kars Merkez", CityId = 36 },
                new District { Id = 493, Name = "Sarıkamış", CityId = 36 },
                new District { Id = 494, Name = "Selim", CityId = 36 },
                new District { Id = 495, Name = "Susuz", CityId = 36 },
                new District { Id = 496, Name = "Akyaka", CityId = 36 },
                new District { Id = 497, Name = "Abana", CityId = 37 },
                new District { Id = 498, Name = "Araç", CityId = 37 },
                new District { Id = 499, Name = "Azdavay", CityId = 37 },
                new District { Id = 500, Name = "Bozkurt / Kastamonu", CityId = 37 },
                new District { Id = 501, Name = "Cide", CityId = 37 },
                new District { Id = 502, Name = "Çatalzeytin", CityId = 37 },
                new District { Id = 503, Name = "Daday", CityId = 37 },
                new District { Id = 504, Name = "Devrekani", CityId = 37 },
                new District { Id = 505, Name = "İnebolu", CityId = 37 },
                new District { Id = 506, Name = "Kastamonu Merkez", CityId = 37 },
                new District { Id = 507, Name = "Küre", CityId = 37 },
                new District { Id = 508, Name = "Taşköprü", CityId = 37 },
                new District { Id = 509, Name = "Tosya", CityId = 37 },
                new District { Id = 510, Name = "İhsangazi", CityId = 37 },
                new District { Id = 511, Name = "Pınarbaşı / Kastamonu", CityId = 37 },
                new District { Id = 512, Name = "Şenpazar", CityId = 37 },
                new District { Id = 513, Name = "Ağlı", CityId = 37 },
                new District { Id = 514, Name = "Doğanyurt", CityId = 37 },
                new District { Id = 515, Name = "Hanönü", CityId = 37 },
                new District { Id = 516, Name = "Seydiler", CityId = 37 },
                new District { Id = 517, Name = "Bünyan", CityId = 38 },
                new District { Id = 518, Name = "Develi", CityId = 38 },
                new District { Id = 519, Name = "Felahiye", CityId = 38 },
                new District { Id = 520, Name = "İncesu", CityId = 38 },
                new District { Id = 521, Name = "Pınarbaşı / Kayseri", CityId = 38 },
                new District { Id = 522, Name = "Sarıoğlan", CityId = 38 },
                new District { Id = 523, Name = "Sarız", CityId = 38 },
                new District { Id = 524, Name = "Tomarza", CityId = 38 },
                new District { Id = 525, Name = "Yahyalı", CityId = 38 },
                new District { Id = 526, Name = "Yeşilhisar", CityId = 38 },
                new District { Id = 527, Name = "Akkışla", CityId = 38 },
                new District { Id = 528, Name = "Talas", CityId = 38 },
                new District { Id = 529, Name = "Kocasinan", CityId = 38 },
                new District { Id = 530, Name = "Melikgazi", CityId = 38 },
                new District { Id = 531, Name = "Hacılar", CityId = 38 },
                new District { Id = 532, Name = "Özvatan", CityId = 38 },
                new District { Id = 533, Name = "Babaeski", CityId = 39 },
                new District { Id = 534, Name = "Demirköy", CityId = 39 },
                new District { Id = 535, Name = "Kırklareli Merkez", CityId = 39 },
                new District { Id = 536, Name = "Kofçaz", CityId = 39 },
                new District { Id = 537, Name = "Lüleburgaz", CityId = 39 },
                new District { Id = 538, Name = "Pehlivanköy", CityId = 39 },
                new District { Id = 539, Name = "Pınarhisar", CityId = 39 },
                new District { Id = 540, Name = "Vize", CityId = 39 },
                new District { Id = 541, Name = "Çiçekdağı", CityId = 40 },
                new District { Id = 542, Name = "Kaman", CityId = 40 },
                new District { Id = 543, Name = "Kırşehir Merkez", CityId = 40 },
                new District { Id = 544, Name = "Mucur", CityId = 40 },
                new District { Id = 545, Name = "Akpınar", CityId = 40 },
                new District { Id = 546, Name = "Akçakent", CityId = 40 },
                new District { Id = 547, Name = "Boztepe", CityId = 40 },
                new District { Id = 548, Name = "Gebze", CityId = 41 },
                new District { Id = 549, Name = "Gölcük", CityId = 41 },
                new District { Id = 550, Name = "Kandıra", CityId = 41 },
                new District { Id = 551, Name = "Karamürsel", CityId = 41 },
                new District { Id = 552, Name = "Körfez", CityId = 41 },
                new District { Id = 553, Name = "Derince", CityId = 41 },
                new District { Id = 554, Name = "Başiskele", CityId = 41 },
                new District { Id = 555, Name = "Çayırova", CityId = 41 },
                new District { Id = 556, Name = "Darıca", CityId = 41 },
                new District { Id = 557, Name = "Dilovası", CityId = 41 },
                new District { Id = 558, Name = "İzmit", CityId = 41 },
                new District { Id = 559, Name = "Kartepe", CityId = 41 },
                new District { Id = 560, Name = "Akşehir", CityId = 42 },
                new District { Id = 561, Name = "Beyşehir", CityId = 42 },
                new District { Id = 562, Name = "Bozkır", CityId = 42 },
                new District { Id = 563, Name = "Cihanbeyli", CityId = 42 },
                new District { Id = 564, Name = "Çumra", CityId = 42 },
                new District { Id = 565, Name = "Doğanhisar", CityId = 42 },
                new District { Id = 566, Name = "Ereğli / Konya", CityId = 42 },
                new District { Id = 567, Name = "Hadim", CityId = 42 },
                new District { Id = 568, Name = "Ilgın", CityId = 42 },
                new District { Id = 569, Name = "Kadınhanı", CityId = 42 },
                new District { Id = 570, Name = "Karapınar", CityId = 42 },
                new District { Id = 571, Name = "Kulu", CityId = 42 },
                new District { Id = 572, Name = "Sarayönü", CityId = 42 },
                new District { Id = 573, Name = "Seydişehir", CityId = 42 },
                new District { Id = 574, Name = "Yunak", CityId = 42 },
                new District { Id = 575, Name = "Akören", CityId = 42 },
                new District { Id = 576, Name = "Altınekin", CityId = 42 },
                new District { Id = 577, Name = "Derebucak", CityId = 42 },
                new District { Id = 578, Name = "Hüyük", CityId = 42 },
                new District { Id = 579, Name = "Karatay", CityId = 42 },
                new District { Id = 580, Name = "Meram", CityId = 42 },
                new District { Id = 581, Name = "Selçuklu", CityId = 42 },
                new District { Id = 582, Name = "Taşkent", CityId = 42 },
                new District { Id = 583, Name = "Ahırlı", CityId = 42 },
                new District { Id = 584, Name = "Çeltik", CityId = 42 },
                new District { Id = 585, Name = "Derbent", CityId = 42 },
                new District { Id = 586, Name = "Emirgazi", CityId = 42 },
                new District { Id = 587, Name = "Güneysınır", CityId = 42 },
                new District { Id = 588, Name = "Halkapınar", CityId = 42 },
                new District { Id = 589, Name = "Tuzlukçu", CityId = 42 },
                new District { Id = 590, Name = "Yalıhüyük", CityId = 42 },
                new District { Id = 591, Name = "Altıntaş", CityId = 43 },
                new District { Id = 592, Name = "Domaniç", CityId = 43 },
                new District { Id = 593, Name = "Emet", CityId = 43 },
                new District { Id = 594, Name = "Gediz", CityId = 43 },
                new District { Id = 595, Name = "Kütahya Merkez", CityId = 43 },
                new District { Id = 596, Name = "Simav", CityId = 43 },
                new District { Id = 597, Name = "Tavşanlı", CityId = 43 },
                new District { Id = 598, Name = "Aslanapa", CityId = 43 },
                new District { Id = 599, Name = "Dumlupınar", CityId = 43 },
                new District { Id = 600, Name = "Hisarcık", CityId = 43 },
                new District { Id = 601, Name = "Şaphane", CityId = 43 },
                new District { Id = 602, Name = "Çavdarhisar", CityId = 43 },
                new District { Id = 603, Name = "Pazarlar", CityId = 43 },
                new District { Id = 604, Name = "Akçadağ", CityId = 44 },
                new District { Id = 605, Name = "Arapgir", CityId = 44 },
                new District { Id = 606, Name = "Arguvan", CityId = 44 },
                new District { Id = 607, Name = "Darende", CityId = 44 },
                new District { Id = 608, Name = "Doğanşehir", CityId = 44 },
                new District { Id = 609, Name = "Hekimhan", CityId = 44 },
                new District { Id = 610, Name = "Pütürge", CityId = 44 },
                new District { Id = 611, Name = "Yeşilyurt / Malatya", CityId = 44 },
                new District { Id = 612, Name = "Battalgazi", CityId = 44 },
                new District { Id = 613, Name = "Doğanyol", CityId = 44 },
                new District { Id = 614, Name = "Kale / Malatya", CityId = 44 },
                new District { Id = 615, Name = "Kuluncak", CityId = 44 },
                new District { Id = 616, Name = "Yazıhan", CityId = 44 },
                new District { Id = 617, Name = "Akhisar", CityId = 45 },
                new District { Id = 618, Name = "Alaşehir", CityId = 45 },
                new District { Id = 619, Name = "Demirci", CityId = 45 },
                new District { Id = 620, Name = "Gördes", CityId = 45 },
                new District { Id = 621, Name = "Kırkağaç", CityId = 45 },
                new District { Id = 622, Name = "Kula", CityId = 45 },
                new District { Id = 623, Name = "Salihli", CityId = 45 },
                new District { Id = 624, Name = "Sarıgöl", CityId = 45 },
                new District { Id = 625, Name = "Saruhanlı", CityId = 45 },
                new District { Id = 626, Name = "Selendi", CityId = 45 },
                new District { Id = 627, Name = "Soma", CityId = 45 },
                new District { Id = 628, Name = "Turgutlu", CityId = 45 },
                new District { Id = 629, Name = "Ahmetli", CityId = 45 },
                new District { Id = 630, Name = "Gölmarmara", CityId = 45 },
                new District { Id = 631, Name = "Köprübaşı / Manisa", CityId = 45 },
                new District { Id = 632, Name = "Şehzadeler", CityId = 45 },
                new District { Id = 633, Name = "Yunusemre", CityId = 45 },
                new District { Id = 634, Name = "Afşin", CityId = 46 },
                new District { Id = 635, Name = "Andırın", CityId = 46 },
                new District { Id = 636, Name = "Elbistan", CityId = 46 },
                new District { Id = 637, Name = "Göksun", CityId = 46 },
                new District { Id = 638, Name = "Pazarcık", CityId = 46 },
                new District { Id = 639, Name = "Türkoğlu", CityId = 46 },
                new District { Id = 640, Name = "Çağlayancerit", CityId = 46 },
                new District { Id = 641, Name = "Ekinözü", CityId = 46 },
                new District { Id = 642, Name = "Nurhak", CityId = 46 },
                new District { Id = 643, Name = "Dulkadiroğlu", CityId = 46 },
                new District { Id = 644, Name = "Onikişubat", CityId = 46 },
                new District { Id = 645, Name = "Derik", CityId = 47 },
                new District { Id = 646, Name = "Kızıltepe", CityId = 47 },
                new District { Id = 647, Name = "Mazıdağı", CityId = 47 },
                new District { Id = 648, Name = "Midyat", CityId = 47 },
                new District { Id = 649, Name = "Nusaybin", CityId = 47 },
                new District { Id = 650, Name = "Ömerli", CityId = 47 },
                new District { Id = 651, Name = "Savur", CityId = 47 },
                new District { Id = 652, Name = "Dargeçit", CityId = 47 },
                new District { Id = 653, Name = "Yeşilli", CityId = 47 },
                new District { Id = 654, Name = "Artuklu", CityId = 47 },
                new District { Id = 655, Name = "Bodrum", CityId = 48 },
                new District { Id = 656, Name = "Datça", CityId = 48 },
                new District { Id = 657, Name = "Fethiye", CityId = 48 },
                new District { Id = 658, Name = "Köyceğiz", CityId = 48 },
                new District { Id = 659, Name = "Marmaris", CityId = 48 },
                new District { Id = 660, Name = "Milas", CityId = 48 },
                new District { Id = 661, Name = "Ula", CityId = 48 },
                new District { Id = 662, Name = "Yatağan", CityId = 48 },
                new District { Id = 663, Name = "Dalaman", CityId = 48 },
                new District { Id = 664, Name = "Ortaca", CityId = 48 },
                new District { Id = 665, Name = "Kavaklıdere", CityId = 48 },
                new District { Id = 666, Name = "Menteşe", CityId = 48 },
                new District { Id = 667, Name = "Seydikemer", CityId = 48 },
                new District { Id = 668, Name = "Bulanık", CityId = 49 },
                new District { Id = 669, Name = "Malazgirt", CityId = 49 },
                new District { Id = 670, Name = "Muş Merkez", CityId = 49 },
                new District { Id = 671, Name = "Varto", CityId = 49 },
                new District { Id = 672, Name = "Hasköy", CityId = 49 },
                new District { Id = 673, Name = "Korkut", CityId = 49 },
                new District { Id = 674, Name = "Avanos", CityId = 50 },
                new District { Id = 675, Name = "Derinkuyu", CityId = 50 },
                new District { Id = 676, Name = "Gülşehir", CityId = 50 },
                new District { Id = 677, Name = "Hacıbektaş", CityId = 50 },
                new District { Id = 678, Name = "Kozaklı", CityId = 50 },
                new District { Id = 679, Name = "Nevşehir Merkez", CityId = 50 },
                new District { Id = 680, Name = "Ürgüp", CityId = 50 },
                new District { Id = 681, Name = "Acıgöl", CityId = 50 },
                new District { Id = 682, Name = "Bor", CityId = 51 },
                new District { Id = 683, Name = "Çamardı", CityId = 51 },
                new District { Id = 684, Name = "Niğde Merkez", CityId = 51 },
                new District { Id = 685, Name = "Ulukışla", CityId = 51 },
                new District { Id = 686, Name = "Altunhisar", CityId = 51 },
                new District { Id = 687, Name = "Çiftlik", CityId = 51 },
                new District { Id = 688, Name = "Akkuş", CityId = 52 },
                new District { Id = 689, Name = "Aybastı", CityId = 52 },
                new District { Id = 690, Name = "Fatsa", CityId = 52 },
                new District { Id = 691, Name = "Gölköy", CityId = 52 },
                new District { Id = 692, Name = "Korgan", CityId = 52 },
                new District { Id = 693, Name = "Kumru", CityId = 52 },
                new District { Id = 694, Name = "Mesudiye", CityId = 52 },
                new District { Id = 695, Name = "Perşembe", CityId = 52 },
                new District { Id = 696, Name = "Ulubey / Ordu", CityId = 52 },
                new District { Id = 697, Name = "Ünye", CityId = 52 },
                new District { Id = 698, Name = "Gülyalı", CityId = 52 },
                new District { Id = 699, Name = "Gürgentepe", CityId = 52 },
                new District { Id = 700, Name = "Çamaş", CityId = 52 },
                new District { Id = 701, Name = "Çatalpınar", CityId = 52 },
                new District { Id = 702, Name = "Çaybaşı", CityId = 52 },
                new District { Id = 703, Name = "İkizce", CityId = 52 },
                new District { Id = 704, Name = "Kabadüz", CityId = 52 },
                new District { Id = 705, Name = "Kabataş", CityId = 52 },
                new District { Id = 706, Name = "Altınordu", CityId = 52 },
                new District { Id = 707, Name = "Ardeşen", CityId = 53 },
                new District { Id = 708, Name = "Çamlıhemşin", CityId = 53 },
                new District { Id = 709, Name = "Çayeli", CityId = 53 },
                new District { Id = 710, Name = "Fındıklı", CityId = 53 },
                new District { Id = 711, Name = "İkizdere", CityId = 53 },
                new District { Id = 712, Name = "Kalkandere", CityId = 53 },
                new District { Id = 713, Name = "Pazar / Rize", CityId = 53 },
                new District { Id = 714, Name = "Rize Merkez", CityId = 53 },
                new District { Id = 715, Name = "Güneysu", CityId = 53 },
                new District { Id = 716, Name = "Derepazarı", CityId = 53 },
                new District { Id = 717, Name = "Hemşin", CityId = 53 },
                new District { Id = 718, Name = "İyidere", CityId = 53 },
                new District { Id = 719, Name = "Akyazı", CityId = 54 },
                new District { Id = 720, Name = "Geyve", CityId = 54 },
                new District { Id = 721, Name = "Hendek", CityId = 54 },
                new District { Id = 722, Name = "Karasu", CityId = 54 },
                new District { Id = 723, Name = "Kaynarca", CityId = 54 },
                new District { Id = 724, Name = "Sapanca", CityId = 54 },
                new District { Id = 725, Name = "Kocaali", CityId = 54 },
                new District { Id = 726, Name = "Pamukova", CityId = 54 },
                new District { Id = 727, Name = "Taraklı", CityId = 54 },
                new District { Id = 728, Name = "Ferizli", CityId = 54 },
                new District { Id = 729, Name = "Karapürçek", CityId = 54 },
                new District { Id = 730, Name = "Söğütlü", CityId = 54 },
                new District { Id = 731, Name = "Adapazarı", CityId = 54 },
                new District { Id = 732, Name = "Arifiye", CityId = 54 },
                new District { Id = 733, Name = "Erenler", CityId = 54 },
                new District { Id = 734, Name = "Serdivan", CityId = 54 },
                new District { Id = 735, Name = "Alaçam", CityId = 55 },
                new District { Id = 736, Name = "Bafra", CityId = 55 },
                new District { Id = 737, Name = "Çarşamba", CityId = 55 },
                new District { Id = 738, Name = "Havza", CityId = 55 },
                new District { Id = 739, Name = "Kavak", CityId = 55 },
                new District { Id = 740, Name = "Ladik", CityId = 55 },
                new District { Id = 741, Name = "Terme", CityId = 55 },
                new District { Id = 742, Name = "Vezirköprü", CityId = 55 },
                new District { Id = 743, Name = "Asarcık", CityId = 55 },
                new District { Id = 744, Name = "19-May", CityId = 55 },
                new District { Id = 745, Name = "Salıpazarı", CityId = 55 },
                new District { Id = 746, Name = "Tekkeköy", CityId = 55 },
                new District { Id = 747, Name = "Ayvacık / Samsun", CityId = 55 },
                new District { Id = 748, Name = "Yakakent", CityId = 55 },
                new District { Id = 749, Name = "Atakum", CityId = 55 },
                new District { Id = 750, Name = "Canik", CityId = 55 },
                new District { Id = 751, Name = "İlkadım", CityId = 55 },
                new District { Id = 752, Name = "Baykan", CityId = 56 },
                new District { Id = 753, Name = "Eruh", CityId = 56 },
                new District { Id = 754, Name = "Kurtalan", CityId = 56 },
                new District { Id = 755, Name = "Pervari", CityId = 56 },
                new District { Id = 756, Name = "Siirt Merkez", CityId = 56 },
                new District { Id = 757, Name = "Şirvan", CityId = 56 },
                new District { Id = 758, Name = "Tillo", CityId = 56 },
                new District { Id = 759, Name = "Ayancık", CityId = 57 },
                new District { Id = 760, Name = "Boyabat", CityId = 57 },
                new District { Id = 761, Name = "Durağan", CityId = 57 },
                new District { Id = 762, Name = "Erfelek", CityId = 57 },
                new District { Id = 763, Name = "Gerze", CityId = 57 },
                new District { Id = 764, Name = "Sinop Merkez", CityId = 57 },
                new District { Id = 765, Name = "Türkeli", CityId = 57 },
                new District { Id = 766, Name = "Dikmen", CityId = 57 },
                new District { Id = 767, Name = "Saraydüzü", CityId = 57 },
                new District { Id = 768, Name = "Divriği", CityId = 58 },
                new District { Id = 769, Name = "Gemerek", CityId = 58 },
                new District { Id = 770, Name = "Gürün", CityId = 58 },
                new District { Id = 771, Name = "Hafik", CityId = 58 },
                new District { Id = 772, Name = "İmranlı", CityId = 58 },
                new District { Id = 773, Name = "Kangal", CityId = 58 },
                new District { Id = 774, Name = "Koyulhisar", CityId = 58 },
                new District { Id = 775, Name = "Sivas Merkez", CityId = 58 },
                new District { Id = 776, Name = "Suşehri", CityId = 58 },
                new District { Id = 777, Name = "Şarkışla", CityId = 58 },
                new District { Id = 778, Name = "Yıldızeli", CityId = 58 },
                new District { Id = 779, Name = "Zara", CityId = 58 },
                new District { Id = 780, Name = "Akıncılar", CityId = 58 },
                new District { Id = 781, Name = "Altınyayla / Sivas", CityId = 58 },
                new District { Id = 782, Name = "Doğanşar", CityId = 58 },
                new District { Id = 783, Name = "Gölova", CityId = 58 },
                new District { Id = 784, Name = "Ulaş", CityId = 58 },
                new District { Id = 785, Name = "Çerkezköy", CityId = 59 },
                new District { Id = 786, Name = "Çorlu", CityId = 59 },
                new District { Id = 787, Name = "Hayrabolu", CityId = 59 },
                new District { Id = 788, Name = "Malkara", CityId = 59 },
                new District { Id = 789, Name = "Muratlı", CityId = 59 },
                new District { Id = 790, Name = "Saray / Tekirdağ", CityId = 59 },
                new District { Id = 791, Name = "Şarköy", CityId = 59 },
                new District { Id = 792, Name = "Marmaraereğlisi", CityId = 59 },
                new District { Id = 793, Name = "Ergene", CityId = 59 },
                new District { Id = 794, Name = "Kapaklı", CityId = 59 },
                new District { Id = 795, Name = "Süleymanpaşa", CityId = 59 },
                new District { Id = 796, Name = "Almus", CityId = 60 },
                new District { Id = 797, Name = "Artova", CityId = 60 },
                new District { Id = 798, Name = "Erbaa", CityId = 60 },
                new District { Id = 799, Name = "Niksar", CityId = 60 },
                new District { Id = 800, Name = "Reşadiye", CityId = 60 },
                new District { Id = 801, Name = "Tokat Merkez", CityId = 60 },
                new District { Id = 802, Name = "Turhal", CityId = 60 },
                new District { Id = 803, Name = "Zile", CityId = 60 },
                new District { Id = 804, Name = "Pazar / Tokat", CityId = 60 },
                new District { Id = 805, Name = "Yeşilyurt / Tokat", CityId = 60 },
                new District { Id = 806, Name = "Başçiftlik", CityId = 60 },
                new District { Id = 807, Name = "Sulusaray", CityId = 60 },
                new District { Id = 808, Name = "Akçaabat", CityId = 61 },
                new District { Id = 809, Name = "Araklı", CityId = 61 },
                new District { Id = 810, Name = "Arsin", CityId = 61 },
                new District { Id = 811, Name = "Çaykara", CityId = 61 },
                new District { Id = 812, Name = "Maçka", CityId = 61 },
                new District { Id = 813, Name = "Of", CityId = 61 },
                new District { Id = 814, Name = "Sürmene", CityId = 61 },
                new District { Id = 815, Name = "Tonya", CityId = 61 },
                new District { Id = 816, Name = "Vakfıkebir", CityId = 61 },
                new District { Id = 817, Name = "Yomra", CityId = 61 },
                new District { Id = 818, Name = "Beşikdüzü", CityId = 61 },
                new District { Id = 819, Name = "Şalpazarı", CityId = 61 },
                new District { Id = 820, Name = "Çarşıbaşı", CityId = 61 },
                new District { Id = 821, Name = "Dernekpazarı", CityId = 61 },
                new District { Id = 822, Name = "Düzköy", CityId = 61 },
                new District { Id = 823, Name = "Hayrat", CityId = 61 },
                new District { Id = 824, Name = "Köprübaşı / Trabzon", CityId = 61 },
                new District { Id = 825, Name = "Ortahisar", CityId = 61 },
                new District { Id = 826, Name = "Çemişgezek", CityId = 62 },
                new District { Id = 827, Name = "Hozat", CityId = 62 },
                new District { Id = 828, Name = "Mazgirt", CityId = 62 },
                new District { Id = 829, Name = "Nazımiye", CityId = 62 },
                new District { Id = 830, Name = "Ovacık / Tunceli", CityId = 62 },
                new District { Id = 831, Name = "Pertek", CityId = 62 },
                new District { Id = 832, Name = "Pülümür", CityId = 62 },
                new District { Id = 833, Name = "Tunceli Merkez", CityId = 62 },
                new District { Id = 834, Name = "Akçakale", CityId = 63 },
                new District { Id = 835, Name = "Birecik", CityId = 63 },
                new District { Id = 836, Name = "Bozova", CityId = 63 },
                new District { Id = 837, Name = "Ceylanpınar", CityId = 63 },
                new District { Id = 838, Name = "Halfeti", CityId = 63 },
                new District { Id = 839, Name = "Hilvan", CityId = 63 },
                new District { Id = 840, Name = "Siverek", CityId = 63 },
                new District { Id = 841, Name = "Suruç", CityId = 63 },
                new District { Id = 842, Name = "Viranşehir", CityId = 63 },
                new District { Id = 843, Name = "Harran", CityId = 63 },
                new District { Id = 844, Name = "Eyyübiye", CityId = 63 },
                new District { Id = 845, Name = "Haliliye", CityId = 63 },
                new District { Id = 846, Name = "Karaköprü", CityId = 63 },
                new District { Id = 847, Name = "Banaz", CityId = 64 },
                new District { Id = 848, Name = "Eşme", CityId = 64 },
                new District { Id = 849, Name = "Karahallı", CityId = 64 },
                new District { Id = 850, Name = "Sivaslı", CityId = 64 },
                new District { Id = 851, Name = "Ulubey / Uşak", CityId = 64 },
                new District { Id = 852, Name = "Uşak Merkez", CityId = 64 },
                new District { Id = 853, Name = "Başkale", CityId = 65 },
                new District { Id = 854, Name = "Çatak", CityId = 65 },
                new District { Id = 855, Name = "Erciş", CityId = 65 },
                new District { Id = 856, Name = "Gevaş", CityId = 65 },
                new District { Id = 857, Name = "Gürpınar", CityId = 65 },
                new District { Id = 858, Name = "Muradiye", CityId = 65 },
                new District { Id = 859, Name = "Özalp", CityId = 65 },
                new District { Id = 860, Name = "Bahçesaray", CityId = 65 },
                new District { Id = 861, Name = "Çaldıran", CityId = 65 },
                new District { Id = 862, Name = "Edremit / Van", CityId = 65 },
                new District { Id = 863, Name = "Saray / Van", CityId = 65 },
                new District { Id = 864, Name = "İpekyolu", CityId = 65 },
                new District { Id = 865, Name = "Tuşba", CityId = 65 },
                new District { Id = 866, Name = "Akdağmadeni", CityId = 66 },
                new District { Id = 867, Name = "Boğazlıyan", CityId = 66 },
                new District { Id = 868, Name = "Çayıralan", CityId = 66 },
                new District { Id = 869, Name = "Çekerek", CityId = 66 },
                new District { Id = 870, Name = "Sarıkaya", CityId = 66 },
                new District { Id = 871, Name = "Sorgun", CityId = 66 },
                new District { Id = 872, Name = "Şefaatli", CityId = 66 },
                new District { Id = 873, Name = "Yerköy", CityId = 66 },
                new District { Id = 874, Name = "Yozgat Merkez", CityId = 66 },
                new District { Id = 875, Name = "Aydıncık / Yozgat", CityId = 66 },
                new District { Id = 876, Name = "Çandır", CityId = 66 },
                new District { Id = 877, Name = "Kadışehri", CityId = 66 },
                new District { Id = 878, Name = "Saraykent", CityId = 66 },
                new District { Id = 879, Name = "Yenifakılı", CityId = 66 },
                new District { Id = 880, Name = "Çaycuma", CityId = 67 },
                new District { Id = 881, Name = "Devrek", CityId = 67 },
                new District { Id = 882, Name = "Ereğli / Zonguldak", CityId = 67 },
                new District { Id = 883, Name = "Zonguldak Merkez", CityId = 67 },
                new District { Id = 884, Name = "Alaplı", CityId = 67 },
                new District { Id = 885, Name = "Gökçebey", CityId = 67 },
                new District { Id = 886, Name = "Kilimli", CityId = 67 },
                new District { Id = 887, Name = "Kozlu", CityId = 67 },
                new District { Id = 888, Name = "Aksaray Merkez", CityId = 68 },
                new District { Id = 889, Name = "Ortaköy / Aksaray", CityId = 68 },
                new District { Id = 890, Name = "Ağaçören", CityId = 68 },
                new District { Id = 891, Name = "Güzelyurt", CityId = 68 },
                new District { Id = 892, Name = "Sarıyahşi", CityId = 68 },
                new District { Id = 893, Name = "Eskil", CityId = 68 },
                new District { Id = 894, Name = "Gülağaç", CityId = 68 },
                new District { Id = 895, Name = "Bayburt Merkez", CityId = 69 },
                new District { Id = 896, Name = "Aydıntepe", CityId = 69 },
                new District { Id = 897, Name = "Demirözü", CityId = 69 },
                new District { Id = 898, Name = "Ermenek", CityId = 70 },
                new District { Id = 899, Name = "Karaman Merkez", CityId = 70 },
                new District { Id = 900, Name = "Ayrancı", CityId = 70 },
                new District { Id = 901, Name = "Kazımkarabekir", CityId = 70 },
                new District { Id = 902, Name = "Başyayla", CityId = 70 },
                new District { Id = 903, Name = "Sarıveliler", CityId = 70 },
                new District { Id = 904, Name = "Delice", CityId = 71 },
                new District { Id = 905, Name = "Keskin", CityId = 71 },
                new District { Id = 906, Name = "Kırıkkale Merkez", CityId = 71 },
                new District { Id = 907, Name = "Sulakyurt", CityId = 71 },
                new District { Id = 908, Name = "Bahşili", CityId = 71 },
                new District { Id = 909, Name = "Balışeyh", CityId = 71 },
                new District { Id = 910, Name = "Çelebi", CityId = 71 },
                new District { Id = 911, Name = "Karakeçili", CityId = 71 },
                new District { Id = 912, Name = "Yahşihan", CityId = 71 },
                new District { Id = 913, Name = "Batman Merkez", CityId = 72 },
                new District { Id = 914, Name = "Beşiri", CityId = 72 },
                new District { Id = 915, Name = "Gercüş", CityId = 72 },
                new District { Id = 916, Name = "Kozluk", CityId = 72 },
                new District { Id = 917, Name = "Sason", CityId = 72 },
                new District { Id = 918, Name = "Hasankeyf", CityId = 72 },
                new District { Id = 919, Name = "Beytüşşebap", CityId = 73 },
                new District { Id = 920, Name = "Cizre", CityId = 73 },
                new District { Id = 921, Name = "İdil", CityId = 73 },
                new District { Id = 922, Name = "Silopi", CityId = 73 },
                new District { Id = 923, Name = "Şırnak Merkez", CityId = 73 },
                new District { Id = 924, Name = "Uludere", CityId = 73 },
                new District { Id = 925, Name = "Güçlükonak", CityId = 73 },
                new District { Id = 926, Name = "Bartın Merkez", CityId = 74 },
                new District { Id = 927, Name = "Kurucaşile", CityId = 74 },
                new District { Id = 928, Name = "Ulus", CityId = 74 },
                new District { Id = 929, Name = "Amasra", CityId = 74 },
                new District { Id = 930, Name = "Ardahan Merkez", CityId = 75 },
                new District { Id = 931, Name = "Çıldır", CityId = 75 },
                new District { Id = 932, Name = "Göle", CityId = 75 },
                new District { Id = 933, Name = "Hanak", CityId = 75 },
                new District { Id = 934, Name = "Posof", CityId = 75 },
                new District { Id = 935, Name = "Damal", CityId = 75 },
                new District { Id = 936, Name = "Aralık", CityId = 76 },
                new District { Id = 937, Name = "Iğdır Merkez", CityId = 76 },
                new District { Id = 938, Name = "Tuzluca", CityId = 76 },
                new District { Id = 939, Name = "Karakoyunlu", CityId = 76 },
                new District { Id = 940, Name = "Yalova Merkez", CityId = 77 },
                new District { Id = 941, Name = "Altınova", CityId = 77 },
                new District { Id = 942, Name = "Armutlu", CityId = 77 },
                new District { Id = 943, Name = "Çınarcık", CityId = 77 },
                new District { Id = 944, Name = "Çiftlikköy", CityId = 77 },
                new District { Id = 945, Name = "Termal", CityId = 77 },
                new District { Id = 946, Name = "Eflani", CityId = 78 },
                new District { Id = 947, Name = "Eskipazar", CityId = 78 },
                new District { Id = 948, Name = "Karabük Merkez", CityId = 78 },
                new District { Id = 949, Name = "Ovacık / Karabük", CityId = 78 },
                new District { Id = 950, Name = "Safranbolu", CityId = 78 },
                new District { Id = 951, Name = "Yenice / Karabük", CityId = 78 },
                new District { Id = 952, Name = "Kilis Merkez", CityId = 79 },
                new District { Id = 953, Name = "Elbeyli", CityId = 79 },
                new District { Id = 954, Name = "Musabeyli", CityId = 79 },
                new District { Id = 955, Name = "Polateli", CityId = 79 },
                new District { Id = 956, Name = "Bahçe", CityId = 80 },
                new District { Id = 957, Name = "Kadirli", CityId = 80 },
                new District { Id = 958, Name = "Osmaniye Merkez", CityId = 80 },
                new District { Id = 959, Name = "Düziçi", CityId = 80 },
                new District { Id = 960, Name = "Hasanbeyli", CityId = 80 },
                new District { Id = 961, Name = "Sumbas", CityId = 80 },
                new District { Id = 962, Name = "Toprakkale", CityId = 80 },
                new District { Id = 963, Name = "Akçakoca", CityId = 81 },
                new District { Id = 964, Name = "Düzce Merkez", CityId = 81 },
                new District { Id = 965, Name = "Yığılca", CityId = 81 },
                new District { Id = 966, Name = "Cumayeri", CityId = 81 },
                new District { Id = 967, Name = "Gölyaka", CityId = 81 },
                new District { Id = 968, Name = "Çilimli", CityId = 81 },
                new District { Id = 969, Name = "Gümüşova", CityId = 81 },
                new District { Id = 970, Name = "Kaynaşlı", CityId = 81 }

            );


        }
    }
}
